select * from customer limit 20

---Q1) What is the total revenue generated by male vs female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

----Q2) Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

----Q3)which are the top 5 products with highest avearge review rationg?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

----Q4)compare the average the standard and express shipping
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

-----Q5)Do subscribe customer spend more?Compare average spend and total revenue between subscribers and non-subscribers
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

-----Q6)Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

----Q7)segment customers into new returning and loyal based on their total numner of previous purchases and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
CASE 
   WHEN previous_purchases = 1 THEN 'New'
   when previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
   ELSE 'Loyal'
   END AS customer_segment
from customer
)
select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment

---Q8)What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;
-----Q9) Calculate month-over-month revenue growth rate
WITH monthly_revenue AS (
    SELECT 
        DATE_TRUNC('month', purchase_date) AS month,
        SUM(purchase_amount) AS revenue
    FROM customer
    GROUP BY month
)

SELECT 
    month,
    revenue,
    LAG(revenue) OVER (ORDER BY month) AS previous_month_revenue,
    ROUND(
        100 * (revenue - LAG(revenue) OVER (ORDER BY month)) 
        / LAG(revenue) OVER (ORDER BY month),2
    ) AS growth_percentage
FROM monthly_revenue
ORDER BY month;
-----Q10) Top 10 customers by lifetime revenue

SELECT 
    customer_id,
    COUNT(*) AS total_orders,
    ROUND(SUM(purchase_amount),2) AS lifetime_revenue
FROM customer
GROUP BY customer_id
ORDER BY lifetime_revenue DESC
LIMIT 10;
-----Q11) Percentage contribution of each category to total revenue

WITH total_revenue AS (
    SELECT SUM(purchase_amount) AS total FROM customer
)

SELECT 
    category,
    ROUND(SUM(purchase_amount),2) AS category_revenue,
    ROUND(
        100 * SUM(purchase_amount) / 
        (SELECT total FROM total_revenue),2
    ) AS revenue_percentage
FROM customer
GROUP BY category
ORDER BY revenue_percentage DESC;
-----Q12) Calculate Customer Lifetime Value

SELECT 
    customer_id,
    ROUND(SUM(purchase_amount),2) AS lifetime_revenue,
    ROUND(AVG(purchase_amount),2) AS avg_order_value,
    COUNT(*) AS frequency
FROM customer
GROUP BY customer_id
ORDER BY lifetime_revenue DESC;
-----Q13) Revenue performance by shipping type

SELECT 
    shipping_type,
    COUNT(*) AS total_orders,
    ROUND(AVG(purchase_amount),2) AS avg_order_value,
    ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY shipping_type
ORDER BY avg_order_value DESC;
-----Q14) Repeat purchase ratio for each product

SELECT 
    item_purchased,
    COUNT(*) AS total_sales,
    COUNT(DISTINCT customer_id) AS unique_customers,
    ROUND(
        COUNT(*)::numeric / 
        COUNT(DISTINCT customer_id),2
    ) AS repeat_purchase_ratio
FROM customer
GROUP BY item_purchased
ORDER BY repeat_purchase_ratio DESC;
-----Q15) Basic RFM segmentation

WITH rfm AS (
SELECT 
    customer_id,
    MAX(purchase_date) AS last_purchase,
    COUNT(*) AS frequency,
    SUM(purchase_amount) AS monetary
FROM customer
GROUP BY customer_id
)

SELECT 
    customer_id,
    CURRENT_DATE - last_purchase AS recency_days,
    frequency,
    monetary,
    CASE 
        WHEN monetary > 1000 THEN 'High Value'
        WHEN monetary BETWEEN 500 AND 1000 THEN 'Mid Value'
        ELSE 'Low Value'
    END AS segment
FROM rfm
ORDER BY monetary DESC;
-----Q21) Revenue trend by weekday vs weekend

SELECT 
    CASE 
        WHEN EXTRACT(DOW FROM purchase_date) IN (0,6) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    ROUND(SUM(purchase_amount),2) AS total_revenue,
    COUNT(*) AS total_orders
FROM customer
GROUP BY day_type;



